# Generated by Django 6.0.6 on 2026-06-17 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0003_categoria_tarefa_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='meu_app.classeativo')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=18)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_transacao', models.DateTimeField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='meu_app.ativo')),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='meu_app.corretora')),
            ],
        ),
    ]
