# Generated by Django 6.0.5 on 2026-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0004_classeativo_corretora_ativo_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='preco_atual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
