# Generated by Django 6.0.5 on 2026-06-28 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0005_ativo_data_ultima_atualizacao_ativo_preco_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='corretora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='meu_app.corretora'),
        ),
    ]
